### ISSUE TITLE
Detect .ino file as Arduino not C++

### ISSUE THREAD

**Issue by pacifiquem** [github-linguist/linguist#6416]
## Current behavior description.

while using .ino files, they are detected as **C++** .

## Expected behavior description.

Actually .ino files must be detected as **Arduino**.

**Comment by pacifiquem** [comment]
those behaviors can be visualized here [RFID Repo ](https://github.com/pacifiquem/RFID).

**Comment by lildude** [comment]
I'm not sure why you chose to ignore the template we provided, but I can confirm this is not a bug. 

This is correct and expected behaviour because because Arduino is not a language.

Linguist used to have support, but this was removed in https://github.com/github-linguist/linguist/pull/3933 with the explanation referenced in https://github.com/github-linguist/linguist/pull/3933 which then associated the `.ino` files with C++.

**Comment by pacifiquem** [comment]
Alright!!
