### ISSUE TITLE
Local repo syntaxes

### ISSUE THREAD

**Issue by Larsouille25** [github-linguist/linguist#6455]
## Describe the enhancement

The thing is that, for people how want to create a programming language, and upload their code on github can't see their code with a highlighted syntax. 

So I propose a local repository syntax : 

In the directory `.github/syntaxes/`, you put your textmate grammar file. And when a file with the extension (specified in the grammar) is open, their is highlighting thanks to the file in .github/syntaxes/.

e.g of a tree with the local syntax :
``` console
$ tree
.
|____*Some code files ...*
|____...
|____.github
| |____syntaxes
| | |____MyProgrammingLanguage.tmLanguage.json
|____LICENSE
```

**Comment by Larsouille25** [comment]
Or with a .gitattributes, like that : 
```gitattributes
*.myopl linguist-syntax https://github.com/[username / organization]/myopl-grammar
```
And in the repo where the grammar is, why not have a special file like `github-linguist.json` where you can find the path to the text mate grammar and some useful data, like the display name, the color etc...

**Comment by lildude** [comment]
This isn't really the right place for this as the syntax highlighting engine is completely independent of Linguist. 

GitHub's syntax highlighting engine is a lightweight, self-contained micro-service which uses cached and consistently transformed grammar files (see the `linguist-grammars.tgz` attachment on each release) and only considers one file in a repo at a time. In order to implement this, it would require the service to read into every single repo to look for the grammar definition, transform it into the form it requires, handle errors etc, and then adjust the rendering. This will be costly in terms of resources, duplicates work linguist's "compiler" does, and would over complicate what is a simple service that works really well.

So whilst a nice idea, it's almost certainly never going to happen, so I'm closing this issue.
