### ISSUE TITLE
Add Power Automate

### ISSUE THREAD

**Issue by diedyesterdaywashere** [github-linguist/linguist#6525]
## Language name

[Power Automate](https://learn.microsoft.com/en-us/power-automate/)  is a visual scripting language, but you can share your flows in a text format.

## URL of example repository

I don't think there's an official sample repo, but i found [this](https://github.com/pnp/powerautomate-samples). But this repo has .zip files that are used to export/import the flow on the web portal, desktop version only supports ctrl+c ctrl+v'ing the flows.

## URL of syntax highlighting grammar

I don't really know if there are any syntax highlighters, but i guess [this](https://github.com/kiingsway/PowerAutomate-Sublime-SyntaxHighlighting) works?

## Most popular extensions

From what i know, they don't have their own extension, but the flow can be distributed in any format, most popular are ``.json`` and ``.txt`` though.

## Detected language

``.txt`` and ``.json`` don't usually get detected automatically.

**Comment by Alhadis** [comment]
I assume your intent is to have repositories categorised as "Power Automate", rather than interpret well-formed JSON files as some format other than JSON (assuming these files aren't concealed inside a ZIP archive, where Linguist isn't going to notice or scan them).

Remember, Linguist's responsibility is to identify file formats and programming languages on a file-by-file basis. Classifying repositories by "project type" (i.e., a Power Automate project) is well beyond Linguist's scope, and is something that [topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) are better suited to.

**Comment by diedyesterdaywashere** [comment]
Alr, thank you!
