### ISSUE TITLE
Incorrect syntax-highlighting of XML files with BOM

### ISSUE THREAD

**Issue by mbtools** [github-linguist/linguist#6561]
### Describe the bug

The `<?xml ... >` tag is not properly colored in some cases. The color of the last character in each attribute name is not correct. It seems the issues occur with XML files that include a [byte-order-mark (BOM)](https://en.wikipedia.org/wiki/Byte_order_mark):

![image](https://github.com/github-linguist/linguist/assets/59966492/5de547fd-eeee-4db5-a32b-9e1be4d3d063)

Example: https://github.com/github-linguist/linguist/blob/master/samples/XML/MDM.admx

### Expected behaviour

Proper highlighting example (XML file without BOM):

![image](https://github.com/github-linguist/linguist/assets/59966492/29aa72fc-b9c5-4176-a0aa-46546e9d273c)

Example: https://github.com/github-linguist/linguist/blob/master/samples/XML/Example.mdpolicy

### XML Grammar

AFAIK, the [XML grammar](https://github.com/textmate/xml.tmbundle/blob/master/Syntaxes/XML.plist) is not responsible for the handling the BOM. Ergo the issue in this repo.

**Comment by lildude** [comment]
This isn't specific to XML and isn't a Linguist or grammar issue. This is a problem with the highlighting engine or rendering of the results where the highlighting of the first line is shifted left by one char (possibly due to miscounting the BOM, but I'm not sure as I'm not familiar with this side of things)... this is easier to see with the `l` in `xml` and the last quote after `1.0`. This has been noted for C++, VB.NET, and F# too in [this discussion](https://github.com/github-linguist/linguist/discussions/6505).

As in that case, please use the "Contact GitHub" link at the bottom of any page to report this to GitHub support who will be able to route this to the correct team. Feel free to reference this issue and the aforementioned discussion.

Closing as there's nothing Linguist can do about this.
