### ISSUE TITLE
Detect vscode-specific JSONC files

### ISSUE THREAD

**Issue by bmuskalla** [github-linguist/linguist#6619]
## Describe the enhancement

VSCode offers a lot of configuration files that are actually JSONC.

See this contribution for a complete list: https://github.com/microsoft/vscode/blob/27a0cbb26647670ad719bcb47e2d1ca4cee133bf/extensions/configuration-editing/package.json#L39

**Comment by lildude** [comment]
This has been attempted before many times and it's not trivial to implement because the filenames are generic with nothing that can be relied upon to 100% correctly identify the file in isolation should be JSONC.

You can see the closed attempts https://github.com/github-linguist/linguist/pulls?q=is%3Apr+jsonc+is%3Aclosed+

Have a read through them to see the challenges we face.

I'm going to close this as not planned as this has been investigated before and there isn't a reliable way of doing this.

You can get the files correctly identified in your repo by implementing an override in the `.gitattributes` file or add a modeline comment to the `.json` files.
