### ISSUE TITLE
Some new languages (luau) don't work when using code search

### ISSUE THREAD

**Issue by solarite1797** [github-linguist/linguist#6890]
## Describe the bug

Ever since the new linguist update, some new languages like Luau don't work when using GitHub's code search.
![image](https://github.com/github-linguist/linguist/assets/118111762/c2b32e83-e327-43dd-81ac-24eea2276b59)
![image](https://github.com/github-linguist/linguist/assets/118111762/ac7138e4-5240-41ed-8367-b8c3bc7b1f0b)

### Expected behaviour

Search should show results for .luau files

**Comment by lildude** [comment]
This is outside of Linguist’s control as Search is completely independent. See https://github.com/github-linguist/linguist/blob/master/docs/troubleshooting.md#when-i-click-on-a-language-present-in-the-language-stats-bar-i-get-a-message-saying-your-search-did-not-match-any-code for more details.

Things have moved on a bit since then as GitHub’s search now uses and internal library for language classification, but the same principle applies.

Closing as this is not within Linguist’s control.
