### ISSUE TITLE
Joy

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6994]
## Language name
Joy

## URL of example repository
https://github.com/Wodan58/Joy

## Most popular extensions
.joy

## Detected language

**Comment by lildude** [comment]
I know all these issues are well intentioned but I'm starting to get the feeling this is a personal project to have an issue for every language that has ever existed that linguist doesn't know about, rather than a genuine desire to add support for languages people are actively developing things in.

We do not add support for hobby languages and have minimum usage requirements (see https://github.com/github-linguist/linguist/issues/5756) we consider for all PRs that add a new language or extension. These issues might tempt someone into contributing only for it to be blocked due to lack of usage which isn't likely to grow as the language may be one that no one uses anymore, if at all.

If you don't feel you can submit a PR to add support for   any of these languages, please limit yourself to only opening issues for languages that meet or are close to meeting or usage requirements.

I'd appreciate it if you could go through [all your issues](https://github.com/github-linguist/linguist/issues?q=is%3Aissue%20state%3Aopen%20author%3AMichaelHinrichs) and close any that are for hobby, dead and unused languages that don't meet our requirements currently and have little prospect of meeting them in the near future.

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
