### ISSUE TITLE
Move is no longer highlighted on GitHub

### ISSUE THREAD

**Issue by damirka** [github-linguist/linguist#7034]
## Describe the bug

Move (added in #5955) is no longer highlighted on GitHub.
[Here's an example of a standard code](https://github.com/sui-potatoes/app/blob/main/packages/codec/sources/base64.move) which was highlighted not so long ago. 

### Expected behaviour

Move should be highlighted.

### Related discussion

Haven't found anything similar, other languages (Solidity, JavaScript, Rust) work.

### Additional notes

The repository name has changed (about a year ago), can that be the case? Old one was `vscode-move-syntax`, now it is just `move-syntax`.

I believe it has something to do with #7021.

**Comment by lildude** [comment]
Sooo, with the Linguist v8.0.0 release, I updated all the grammars as normal, which included an update to the Move grammar.

Looking at the tarball of the compiled grammars which we pass to the syntax highlighter, it looks like the grammar compiler has found the [`simple.move.tmLanguage.json`](https://github.com/damirka/move-syntax/blob/0cff4af858fc827ad7cc09729d09cdca81934f6e/syntaxes/simple.move.tmLanguage.json) file and used that for the `source.move` scope:

```console
➜ cat source.move.json | jq
{
  "scopeName": "source.move",
  "repository": {
    "block-comments": {
      "patterns": [
        {
          "name": "comment.block.documentation.move",
          "begin": "/\\*[\\*!](?![\\*/])",
          "end": "\\*/"
        },
        {
          "name": "comment.block.move",
          "begin": "/\\*",
          "end": "\\*/"
        }
      ]
    },
    "comments": {
      "name": "meta.comments.move",
      "patterns": [
        {
          "include": "#line-comments"
        },
        {
          "include": "#block-comments"
        }
      ]
    },
    "line-comments": {
      "name": "comment.line.double-slash.move",
      "begin": "//",
      "end": "$"
    }
  }
}
```

This has happened because that repo now has two grammars with identical scopeNames of `source.move`: `simple.move.tmLanguage.json` and `move.tmLanguage.json`. This is wrong as there's no way for the grammar compiler to know which one to use and in fact uses both, but as `simple.move.tmLanguage.json` is alphabetically later than the `move.tmLanguage.json`, it overwrites the former with the latter.

It looks like you added this file in https://github.com/damirka/move-syntax/commit/7909b9096669930da1c9c08a2202e991c7187bfe

There's no quick fix... you need to either remove the `simple.move.tmLanguage.json` grammar or give it a different scopeName. Once done, the changes will be picked up in the next Linguist release.

**Comment by juzybits** [comment]
@lildude, would it be possible to do a patch release to fix the issue? Lots of Move devs will be affected by the lack of proper highlighting.

**Comment by lildude** [comment]
> So there's absolutely nothing to do except waiting for the next release? 

Yup

> And is there a plan / deadline for it?

I normally make a release once a quarter. I can make a patch release but it probably won't be until end of next week at the earliest, most likely early the week after, as it's not the simplest of tasks and requires me to free up time in my work schedule.

I'll do it as soon as I can.

**Comment by juzybits** [comment]
Thanks a lot @lildude!

**Comment by damirka** [comment]
> I normally make a release once a quarter. I can make a patch release but it probably won't be until end of next week at the earliest, most likely early the week after, as it's not the simplest of tasks and requires me to free up time in my work schedule.

Myself and a lot of folks would greatly appreciate the effort. If there's anything I can do to help, will do gladly.

**Comment by fmhall** [comment]
This would be greatly appreciated, thank you!

**Comment by lildude** [comment]
Syntax highlighting is working for all Move files again.
